package chapter14;

public class Exercise14_3Excption extends Exception {

	public void errMessage() {
		System.out.println("プログラムで例外が発生しました。");
	}

}
